{{- if and .Values.persistence.enabled (not .Values.persistence.existingClaim) }}
{{- if not .Values.persistence.useVolumeClaimTemplates }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "helios.fullname" . }}-pvc
  labels:
    {{- include "helios.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  {{- if .Values.persistence.storageClass }}
  storageClassName: {{ .Values.persistence.storageClass }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
{{- end }}
{{- end }}
