apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: heliosclients.blockchain.obol.tech
spec:
  group: blockchain.obol.tech
  names:
    kind: HeliosClient
    listKind: HeliosClientList
    plural: heliosclients
    singular: heliosclient
    shortNames:
      - hc
  scope: Namespaced
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              required:
                - network
                - executionRpc
              properties:
                network:
                  type: string
                  description: "Ethereum network (mainnet, sepolia, holesky)"
                  enum:
                    - mainnet
                    - sepolia
                    - holesky
                executionRpc:
                  type: string
                  description: "Execution layer RPC endpoint (must support eth_getProof)"
                consensusRpc:
                  type: string
                  description: "Consensus layer RPC endpoint"
                checkpoint:
                  type: string
                  description: "Weak subjectivity checkpoint"
                rpcPort:
                  type: integer
                  description: "RPC port for the local server"
                  minimum: 1
                  maximum: 65535
                rpcBindIp:
                  type: string
                  description: "IP to bind the RPC server to"
                dataDir:
                  type: string
                  description: "Directory for storing cached checkpoints"
                strictCheckpointAge:
                  type: boolean
                  description: "Whether to enable strict checkpoint age checking"
                persistence:
                  type: object
                  properties:
                    enabled:
                      type: boolean
                    size:
                      type: string
                    storageClass:
                      type: string
                resources:
                  type: object
                  properties:
                    requests:
                      type: object
                      properties:
                        cpu:
                          type: string
                        memory:
                          type: string
                    limits:
                      type: object
                      properties:
                        cpu:
                          type: string
                        memory:
                          type: string
            status:
              type: object
              properties:
                conditions:
                  type: array
                  items:
                    type: object
                    required:
                      - type
                      - status
                    properties:
                      type:
                        type: string
                      status:
                        type: string
                      reason:
                        type: string
                      message:
                        type: string
                      lastTransitionTime:
                        type: string
                phase:
                  type: string
                  enum:
                    - Pending
                    - Running
                    - Syncing
                    - Ready
                    - Failed
      additionalPrinterColumns:
        - name: Network
          type: string
          jsonPath: .spec.network
        - name: Status
          type: string
          jsonPath: .status.phase
        - name: Age
          type: date
          jsonPath: .metadata.creationTimestamp
      subresources:
        status: {}
