{{- if .Values.prometheus.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: prometheus
  namespace: {{ .Release.Namespace }}
  labels:
    app: prometheus

spec:
    type: ClusterIP
    ports:
    - port: 9090
      targetPort: 9090
      protocol: TCP
      name: http-web
    selector:
        app: prometheus
        release: {{ .Release.Name }}
{{- end }}
