apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.clusterlock | default "cluster-lock" }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "charon.labels" . | nindent 4 }}
type: Opaque
data:
  # IMPORTANT: The 'cluster-lock.json' key below MUST be populated with the
  # base64 encoded content of your cluster definition file (e.g., cluster-definition.json or cluster-lock.json).
  # This file is generated during the Distributed Key Generation (DKG) process using 'charon create dkg'
  # or 'charon create cluster'.
  #
  # How to populate this:
  # 1. After running DKG, you will have a cluster definition file (often named cluster-definition.json or cluster-lock.json).
  # 2. Base64 encode the content of this file.
  #    - On Linux:   cat /path/to/your/cluster-definition.json | base64 -w0
  #    - On macOS:   cat /path/to/your/cluster-definition.json | base64
  # 3. Paste the resulting base64 string as the value for 'cluster-lock.json' below, replacing the empty string.
  #
  # If this data is not provided or is incorrect, Charon will fail to start, likely with an error message such as:
  # "Fatal error: load cluster manifest: load dag from disk: no file found" or similar parsing errors.
  #
  # This Helm chart does NOT automatically generate or populate the cluster definition data.
  # The DKG ceremony and the subsequent population of this secret are manual steps performed by the user.
  #
  # --- REPLACE THE EMPTY STRING BELOW WITH YOUR ACTUAL BASE64 ENCODED CLUSTER DEFINITION ---
  cluster-lock.json: "eyJjbHVzdGVyX2RlZmluaXRpb24iOnsidXVpZCI6IjAwMDAwMDAwLTAwMDAtMDAwMC0wMDAwLTAwMDAwMDAwMDAwMCIsInZlcnNpb24iOiJ2MS44LjAiLCJvcGVyYXRvcnMiOltdfSwiZGlzdHJpYnV0ZWRfdmFsaWRhdG9ycyI6W10sImxvY2tfaGFzaCI6IjB4MDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAifQ=="
