{{- if .Values.rbac.enabled }}
{{- range $i := until (int .Values.clusterSize) }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "relay.serviceAccountName" $ }}-{{ $i }}
  labels:
    name: {{ include "release.name" $ }}-{{ $i }}
rules:
{{- toYaml $.Values.rbac.clusterRules | nindent 0 }}
{{- end }}
{{- end }}
