{{- if .Values.podDisruptionBudget.enabled }}
{{- range $i := until (int .Values.clusterSize) }}
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "relay.fullname" $ }}-{{ $i }}
  namespace: {{ $.Release.Namespace }}
  labels:
    name: {{ include "release.name" $ }}-{{ $i }}
spec:
{{- if $.Values.podDisruptionBudget.minAvailable }}
  minAvailable: {{ $.Values.podDisruptionBudget.minAvailable }}
{{- end }}
{{- if $.Values.podDisruptionBudget.maxUnavailable }}
  maxUnavailable: {{ $.Values.podDisruptionBudget.maxUnavailable }}
{{- end }}
  selector:
    matchLabels:
      name: {{ include "release.name" $ }}-{{ $i }}
{{- end }}
{{- end }}
