{{- if .Values.rbac.enabled }}
{{- range $i := until (int .Values.clusterSize) }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "relay.serviceAccountName" $ }}-{{ $i }}
  namespace: {{ $.Release.Namespace }}
rules:
{{- toYaml $.Values.rbac.rules | nindent 0 }}
{{- end }}
{{- end }}
