{{ range 0 until .Values.clusterSize }}
{{- if .Values.rbac.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "relay.serviceAccountName" . }}
  labels:
    {{- include "relay.labels" . | nindent 4 }}
rules:
{{- toYaml .Values.rbac.rules | nindent 0 }}
{{- end }}
{{- end }}