{{- if .Values.serviceAccount.enabled -}}
{{- range $i := until (int .Values.clusterSize) }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "relay.serviceAccountName" $ }}-{{ $i }}
  namespace: {{ $.Release.Namespace }}
  labels:
    name: {{ include "release.name" $ }}-{{ $i }}
{{- end }}
{{- end }}
