{{- if .Values.serviceMonitor.enabled }}
{{- range $i := until (int .Values.clusterSize) }}
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "relay.serviceAccountName" $ }}-{{ $i }}
  {{- if $.Values.serviceMonitor.namespace }}
  namespace: {{ $.Values.serviceMonitor.namespace }}
  {{- end }}
  labels:
    name: {{ include "release.name" $ }}-{{ $i }}
  {{- if $.Values.serviceMonitor.annotations }}
  annotations:
  {{- toYaml $.Values.serviceMonitor.annotations | nindent 4 }}
  {{- end }}
spec:
  endpoints:
  - interval: {{ $.Values.serviceMonitor.interval }}
    {{- if $.Values.serviceMonitor.scrapeTimeout }}
    scrapeTimeout: {{ $.Values.serviceMonitor.scrapeTimeout }}
    {{- end }}
    honorLabels: true
    port: metrics
    path: {{ $.Values.serviceMonitor.path }}
    scheme: {{ $.Values.serviceMonitor.scheme }}
    {{- if $.Values.serviceMonitor.tlsConfig }}
    tlsConfig:
    {{- toYaml $.Values.serviceMonitor.tlsConfig | nindent 6 }}
    {{- end }}
    {{- if $.Values.serviceMonitor.relabelings }}
    relabelings:
    {{- toYaml $.Values.serviceMonitor.relabelings | nindent 4 }}
    {{- end }}
  jobLabel: "{{ $.Release.Name }}"-{{ $i }}
  selector:
    matchLabels:
      name: {{ include "release.name" $ }}-{{ $i }}
  namespaceSelector:
    matchNames:
      - {{ $.Release.Namespace }}
{{- end }}
{{- end }}
