{{- if not .Values.clusterSize }}
{{- fail ".Values.clusterSize is required" }}
{{- end }}

{{- if .Values.centralMonitoring.enabled }}
{{- if and (not .Values.centralMonitoring.token) (not .Values.centralMonitoring.existingSecret.name) }}
{{- fail ".Values.centralMonitoring.token or .Values.centralMonitoring.existingSecret.name is required when centralMonitoring is enabled" }}
{{- end }}
{{- end }}
