{{- if not .Values.clusterSize }}
{{- fail ".Values.clusterSize is required" }}
{{- end }}

{{- if .Values.centralMonitoring.enabled }}
{{- if not .Values.centralMonitoring.token }}
{{- fail ".Values.centralMonitoring.token is required" }}
{{- end }}
{{- end }}
