apiVersion: apps/v1
kind: Deployment
metadata:
  name: dkg-mock-api
  namespace: test-charon
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dkg-mock-api
  template:
    metadata:
      labels:
        app: dkg-mock-api
    spec:
      containers:
      - name: dkg-mock-api
        image: dkg-mock-api:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 3001
        env:
        - name: PORT
          value: "3001"
        - name: MOCK_DKG_STATE
          value: "FULLY_SIGNED"
---
apiVersion: v1
kind: Service
metadata:
  name: test-charon-cluster-dkg-mock-api-service
  namespace: test-charon
spec:
  selector:
    app: dkg-mock-api
  ports:
  - port: 3001
    targetPort: 3001