{{- if .Values.centralMonitoring.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "release.name" . }}-prometheus
spec:
  ports:
  - port: 9090
    protocol: TCP
    targetPort: 9090
  selector:
    app: {{ include "release.name" . }}-prometheus
  sessionAffinity: None
  type: ClusterIP
{{- end }}
