{{- if not .Values.config.beaconNodeEndpoints }}
{{- fail ".Values.config.beaconNodeEndpoints is required" }}
{{- end }}

{{- if not .Values.secrets.validatorKeys }}
{{- fail ".Values.secrets.validatorKeys is required" }}
{{- end }}

{{- if not .Values.secrets.enrPrivateKey }}
{{- fail ".Values.secrets.enrPrivateKey is required" }}
{{- end }}

{{- if not .Values.secrets.clusterlock }}
{{- fail ".Values.secrets.clusterlock is required" }}
{{- end }}

{{- if .Values.serviceAccount.enabled -}}
  {{- if not .Values.serviceAccount.name }}
  {{- fail ".Values.serviceAccount.name is required" }}
  {{- end }}
{{- end }}
