{{- if not .Values.global.jwtSecret }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "lido-charon-dv-node.fullname" . }}-jwt-init
  labels:
    {{- include "lido-charon-dv-node.labels" . | nindent 4 }}
data:
  init-jwt.sh: |
    #!/bin/sh
    set -e
    
    # Check if JWT secret already exists
    if [ -f /jwt/jwt.hex ]; then
      echo "JWT secret already exists, skipping generation"
      exit 0
    fi
    
    echo "Generating JWT secret..."
    openssl rand -hex 32 > /jwt/jwt.hex
    chmod 600 /jwt/jwt.hex
    echo "JWT secret generated successfully"
{{- end }}