{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "lido-charon-dv-node.fullname" . }}
  labels:
    {{- include "lido-charon-dv-node.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "lido-charon-dv-node.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "lido-charon-dv-node.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}